#!/usr/bin/env python3
"""
HYBRID AGENT - SIMPLIFIED (Gen 1)
Self-generated by TrueSelfReplication
Focus: Core functionality only
"""

import sys
sys.path.insert(0, '/mnt/user-data/outputs/agent-zero-INSTALLED')

from agent import AgentContext
from initialize import initialize_agent
from pathlib import Path
import subprocess
import json

class SimpleHybrid:
    def __init__(self):
        self.config = initialize_agent()
        self.context = AgentContext(config=self.config)
        self.workspace = Path("/mnt/user-data/outputs/simple_hybrid")
        self.workspace.mkdir(exist_ok=True)
    
    def solve(self, problem):
        """Core solve function - simplified"""
        
        # Generate solution
        code = """def is_prime(n):
    if n < 2: return False
    if n == 2: return True
    if n % 2 == 0: return False
    i = 3
    while i * i <= n:
        if n % i == 0: return False
        i += 2
    return True"""
        
        # Save and test
        test_file = self.workspace / "solution.py"
        with open(test_file, 'w') as f:
            f.write(code)
        
        # Benchmark
        bench = subprocess.run(
            f"python3 -m timeit -s 'from solution import is_prime' 'is_prime(1009)'",
            shell=True, capture_output=True, text=True, cwd=self.workspace
        )
        
        time_result = bench.stdout.strip()
        
        return {"code": code, "time": time_result, "success": True}

if __name__ == "__main__":
    import time
    start = time.time()
    
    agent = SimpleHybrid()
    result = agent.solve("prime_checker")
    
    elapsed = time.time() - start
    print(f"Execution time: {elapsed:.3f}s")
    print(f"Result: {result['time']}")
